# Generated by Django 5.2.11 on 2026-02-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
