# Generated by Django 5.2.11 on 2026-02-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0002_otp_password_otp_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
    ]
