# Generated by Django 5.2.11 on 2026-02-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0004_alter_otp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='username',
        ),
    ]
