# Generated by Django 5.2.11 on 2026-02-06 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0005_remove_otp_password_remove_otp_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('pairing_code', models.CharField(max_length=4)),
                ('screen_time_limit', models.IntegerField(default=60)),
                ('is_paired', models.BooleanField(default=False)),
                ('parent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
