# Generated by Django 5.2.11 on 2026-02-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0007_rename_parent_email_child_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='child',
            name='lastname',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
