# Generated by Django 5.2.11 on 2026-02-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0008_rename_name_child_firstname_child_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='pairingCode',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
