# Generated by Django 5.2.11 on 2026-02-06 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0009_child_pairingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingcode',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='the_watcher.child'),
        ),
    ]
