# Generated by Django 5.2.11 on 2026-03-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0013_alert_parent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='parent_email',
        ),
    ]
