# Generated by Django 5.2.11 on 2026-04-26 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0014_remove_alert_parent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='appUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_time', models.IntegerField(default=0)),
                ('package_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_watcher.child')),
            ],
        ),
        migrations.DeleteModel(
            name='appUasge',
        ),
    ]
