# Generated by Django 6.0.5 on 2026-05-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0015_appusage_delete_appuasge'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusage',
            name='action',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appusage',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appusage',
            name='risk',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
