# Generated by Django 6.0.5 on 2026-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0016_appusage_action_appusage_category_appusage_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
