# Generated by Django 6.0.5 on 2026-05-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0017_child_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='webUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_time', models.IntegerField(default=0)),
                ('url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk', models.CharField(max_length=20, null=True)),
                ('action', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_watcher.child')),
            ],
        ),
    ]
