# Generated by Django 6.0.5 on 2026-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0018_webusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='webusage',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webusage',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
