# Generated by Django 5.2.14 on 2026-05-28 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0019_webusage_reasoning_alter_webusage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('risk', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_watcher.child')),
            ],
        ),
    ]
