# Generated by Django 5.2.14 on 2026-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0020_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='deactivate_command',
            field=models.BooleanField(default=False),
        ),
    ]
