# Generated by Django 6.0.6 on 2026-06-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0021_child_deactivate_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='admin_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
