# Generated by Django 6.0.6 on 2026-06-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0022_child_admin_disabled_child_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
