# Generated by Django 6.0.6 on 2026-06-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0023_alert_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='bedtime_end',
            field=models.TimeField(blank=True, default='07:00', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='bedtime_start',
            field=models.TimeField(blank=True, default='21:00', null=True),
        ),
    ]
