# Generated by Django 6.0.6 on 2026-06-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0024_child_bedtime_end_child_bedtime_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='bedtime_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
