# Generated by Django 6.0.6 on 2026-06-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0025_child_bedtime_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
