# Generated by Django 6.0.6 on 2026-06-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0027_parentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
