# Generated by Django 6.0.6 on 2026-06-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_watcher', '0028_child_parent_unlocked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webusage',
            name='usage_time',
        ),
    ]
