from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup_api),
    path('login/', views.login_api),
    path('checkEmail/', views.checkEmail_api),
    path('resetPassword/', views.resetPassword_api),
    #path('generateOtp/', views.otpGeneration_api),
    path('verifyOtp/', views.otpVerification_api),
    path('resendOtp/', views.resendOtp_api),
    path('createChild/', views.createChild_api),
    path('pairDevice/', views.pairingCodeVerification_api),
    path('fetchChildren/', views.fetchChildren_api),
    path('appdata/',views.collectAppUsageData_Api),
    path('sendalert/',views.create_alert),
    path('childusage/<int:child_id>/', views.get_child_usage),
    path('collectwebusage/', views.collect_web_usage),
    path('collectchat/', views.collect_chat),
    path('api/deactivate-admin/', views.deactivate_child_admin),
    path('api/check-command/', views.check_deactivate_command ),
    path('heartbeat/', views.heartbeat_api, ),
    path('check-lock-status/', views.check_lock_status),
    path('unlock-device/', views.unlock_device),
    path('lock-device/', views.lock_device),
    path('dashboard-summary/', views.dashboard_summary_api),
    path('browsing-monitoring/', views.browsing_monitoring_api),
    path('fetch-alerts/', views.fetchAlerts_api),
    path('report-device-status/', views.report_device_status),
    path('get-child-usage/<int:child_id>/', views.get_child_usage),
    path('get-screen-limits/', views.get_screen_limits),
    path('update-screen-limits/', views.update_screen_limits),
    path('fetch-chat-messages/', views.fetch_chat_messages),
    path('youtube-activity/', views.youtube_activity_api),

]